package com.envelo.task.model.actioans;

public enum ActionName {
    GET_ALL_ACTIONS,
    GET_ALL_RATES,
    GET_RATES_BY_CODE,
    FETCH_RATES_FROM_API,
    GET_ALL_CURRENCIES_FROM_ALLOW__LIST,
    CONVERSION_TO_PLN,
    CONVERSION_TO_CURRENCY,
    SAVE_CURRENCY_TO_ALLOW_LIST,
    DELETE_CURRENCY_FROM_ALLOW_LIST
}
